### PR TITLE
Create CITATION.cff

### PR DESCRIPTION
**Pull request by jbusecke**
Pinging @aaronspring @markusritschel @keewis @TomNicholas @emaroon. Could you please add your Full names and ORCIDs for easier citation?

Thanks

### CODE REVIEW

**Comment by TomNicholas** [comment]
https://github.com/xgcm/xgcm/issues/449#issuecomment-1069346004

**Comment by keewis** [comment]
see `cf-xarray`'s [`CITATION.cff`](https://github.com/xarray-contrib/cf-xarray/blob/d15ea92362cc79c996377f55abe54bc8b93717b5/CITATION.cff#L31-L34)

**Comment by markusritschel** [comment]
Markus Ritschel
0000-0001-7464-7075
Universität Hamburg, Germany

**Comment by emaroon** [comment]
Elizabeth Maroon 
0000-0002-1660-7822

**Comment by aaronspring** [comment]
Aaron Spring https://orcid.org/0000-0003-0216-2241

**Comment by jbusecke** [comment]
Ok I added you all here. Will merge as I need the new citation relatively quickly, but please ping me if something went wrong here.

**Pull request merged**
